version: "3"
tasks:
  default:
    - task: brew
    - task: zsh
    - task: tmux
    - task: mise
    - task: ruby
    - task: textlint
  brew:
    cmds:
      - brew bundle
    interactive: true
  zsh:
    cmds:
      # install oh-my-zsh
      - cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        ignore_error: true
      - stow -vv -t ~/ zsh
    interactive: true
  tmux:
    cmds:
      - stow -vv -t ~/ tmux
  mise:
    cmds:
      - mise use -g node@22
      - mise use -g python@3
      - mise use -g ruby@3
      - mise use -g go@1
  ruby:
    cmds:
      - stow -vv -t ~/ ruby
  textlint:
    cmds:
      - npm install -g textlint textlint-rule-ginger textlint-rule-spellchecker
      - stow -vv -t ~/ textlint
